version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - pg-dataset:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    ports:
      - "${PGADMIN_PORT_NUMBER:-80}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  pg-dataset:
